# Generated by Django 6.0.4 on 2026-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruble_to_usd_buying', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('usd_to_kwacha_selling', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('kwacha_to_usd_buying', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('usd_to_ruble_selling', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
            },
        ),
        migrations.CreateModel(
            name='RateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruble_to_usd_buying', models.DecimalField(decimal_places=6, max_digits=18)),
                ('usd_to_kwacha_selling', models.DecimalField(decimal_places=6, max_digits=18)),
                ('kwacha_to_usd_buying', models.DecimalField(decimal_places=6, max_digits=18)),
                ('usd_to_ruble_selling', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rate Audit Log',
                'verbose_name_plural': 'Rate Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
