# Generated by Django 5.1.1 on 2026-05-02 03:22

from decimal import Decimal
from django.db import migrations, models


def seed_platform_settings(apps, schema_editor):
    PlatformSettings = apps.get_model("rates", "PlatformSettings")
    PlatformSettings.objects.get_or_create(
        id=1,
        defaults={"commission_rate": Decimal("0.045000")},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_extension_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=6, default=Decimal('0.045000'), max_digits=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
            },
        ),
        migrations.RunPython(seed_platform_settings, migrations.RunPython.noop),
    ]
