# Generated by Django 5.1.1 on 2026-04-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recipient',
            new_name='recipients__user_id_d338ff_idx',
            old_name='rcp_user_active_idx',
        ),
    ]
