# Generated by Django 5.1.1 on 2026-05-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_recipient_contact_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recipient',
            new_name='recipients__owner_i_507911_idx',
            old_name='recipients_owner_idx',
        ),
        migrations.AlterField(
            model_name='recipient',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
