# Generated by Django 6.0.4 on 2026-04-11 16:48

import transactions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('russia-zambia', 'Russia → Zambia'), ('zambia-russia', 'Zambia → Russia')], max_length=20)),
                ('input_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('input_currency', models.CharField(choices=[('RUB', 'Russian Ruble'), ('ZMW', 'Zambian Kwacha'), ('USD', 'US Dollar')], max_length=3)),
                ('result_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('result_currency', models.CharField(choices=[('RUB', 'Russian Ruble'), ('ZMW', 'Zambian Kwacha'), ('USD', 'US Dollar')], max_length=3)),
                ('commission_rate', models.DecimalField(decimal_places=4, default='0.0450', max_digits=5)),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pop_not_uploaded', 'Awaiting POP'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pop_not_uploaded', max_length=25)),
                ('pop_file', models.FileField(blank=True, null=True, upload_to=transactions.models.pop_upload_path)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to=transactions.models.receipt_upload_path)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
