# Generated by Django 5.1.1 on 2026-05-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_extension_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting confirmation'), ('pop_not_uploaded', 'Awaiting POP'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
