# Generated by Django 5.1.1 on 2026-05-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_phase3_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof_deadline_at',
            field=models.DateTimeField(blank=True, help_text='When set, POP must be uploaded before this time or the transfer is canceled.', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting confirmation'), ('pop_not_uploaded', 'Awaiting POP'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
    ]
